// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxGjidPfQoa2-n_SSe3O05zHglPvx2wkU',
    appId: '1:226457735565:web:84c4768d528e95bfb26dc4',
    messagingSenderId: '226457735565',
    projectId: 'fir-demo-c234c',
    authDomain: 'fir-demo-c234c.firebaseapp.com',
    storageBucket: 'fir-demo-c234c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTrv21p1Fy4X2zFozmfgtNcgL-m7KdCq0',
    appId: '1:226457735565:android:3b2e333bdc329c8fb26dc4',
    messagingSenderId: '226457735565',
    projectId: 'fir-demo-c234c',
    storageBucket: 'fir-demo-c234c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0IeTlzDyZGxJsPrppdGZqbyUrMQrJCBg',
    appId: '1:226457735565:ios:22b3f70f52fc44d6b26dc4',
    messagingSenderId: '226457735565',
    projectId: 'fir-demo-c234c',
    storageBucket: 'fir-demo-c234c.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0IeTlzDyZGxJsPrppdGZqbyUrMQrJCBg',
    appId: '1:226457735565:ios:d6bc64a4451e33dfb26dc4',
    messagingSenderId: '226457735565',
    projectId: 'fir-demo-c234c',
    storageBucket: 'fir-demo-c234c.appspot.com',
    iosBundleId: 'com.example.firebaseDemo.RunnerTests',
  );
}
